name: MerchForce
description: This is a program made to keep track of remote staff using gps capabilities.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  css_colors: ^1.0.2
  http: ^0.13.4
  google_fonts: ^3.0.1
  mapbox_gl: ^0.16.0
  cached_network_image: ^3.2.1
  flutter_osm_plugin: ^0.37.2+1
  latlong: ^0.6.1
  latlong2: ^0.8.1
  flutter_map_marker_cluster:
  location:
  flutter_map:
  postgres: ^2.4.5
  geolocator: ^9.0.1
  sqflite:
  path:
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logodesigna.png
    - assets/Business_2_(89).jpg
    - assets/vecteezy_flat-clock-alarm-watch-vector-illustration_.jpg
    - assets/applogodesign.png
    - assets/placeholder.jpg
    - assets/free.jpg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


